# =======================================================
# Source: Submerged LYSO Crystal (Self-Decay of Lu-176)
# =======================================================
/gps/particle ion
# Z=71 (Lutetium), A=176
/gps/ion 71 176

# Set position to match the bounding box of the STL
/gps/pos/type Volume
/gps/pos/shape Para          

# 精確 STL 中心點坐標 (X=0, Y=0, Z=36.93 mm)
/gps/pos/centre 0.0 36.93 0.0 mm    

# 半長度 (稍微加大 0.01 mm 確保 Bounding Box 完全包覆 STL 表面，避免漏計)
/gps/pos/halfx 2.01 mm
/gps/pos/halfy 10.01 mm
/gps/pos/halfz 2.01 mm

# 嚴格限制只能喺 LYSO 物理幾何內生成
/gps/pos/confine LYSO_calor_unit_0

# Set primary ion kinetic energy to 0 MeV 
/gps/ene/type Mono
/gps/ene/mono 0. MeV

# Allow isotropic emission
/gps/ang/type iso