/run/numberOfThreads 20
/run/initialize

# Enable command echo
/control/verbose 0

#/gps/verbose 2
#Set the General Particle Source to be Na22
/gps/particle gamma

#Position region of generated gps, should equal to the active region
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0 0 0 mm
/gps/pos/radius 4.765 mm
/gps/pos/halfz 0.0001 mm

#Set the energy distribution of Source, Mono (single value)
/gps/ene/type Mono
/gps/energy 1.27 MeV

#Set the direction distribution of Source
/gps/ang/type iso
#/gps/ang/mintheta 0 degree
#/gps/ang/maxtheta 180 degree
#/gps/ang/minphi 0 degree
#/gps/ang/maxphi 360 degree
# Run commands
/run/beamOn 100000 # originally 1.85 MBq, now about 2.6 year, so 680577 c/s, 0.01 second=6806